### ISSUE TITLE
Recursive dependancy detected when dependant target's dependancy is also depended on from the original target.

### ISSUE THREAD

**Issue by markembling** [JeremySkinner/Phantom#6]
The following build script fails:

```
target default, (compile, test):
    pass

target compile:
    msbuild(....)

target test, (compile):
    ....
```

Phantom output:

```
Phantom v0.1.0.0
Copyright (c) Jeremy Skinner 2009 (http://www.jeremyskinner.co.uk)
http://github.com/JeremySkinner/Phantom


Targets specified: default


Phantom.Core.PhantomException: Detected recursive dependency for target 'compile'
   at Phantom.Core.Target.PopulateExecutionSequence(ICollection`1 sequence)
   at Phantom.Core.Target.GetExecutionSequence()
   at Phantom.Core.ScriptModel.ExecuteTargets(String[] targetNames)
   at Phantom.Program.Execute(String[] args)
```

I would expect a script with a dependancy situation such as this to be resolvable.

**Comment by JeremySkinner** [comment]
Fixed in latest commit.
